Use constant for array size in os-linux
When cross-compiling for Linux on Windows using VC toolchain
(in dotnet/runtime), we get the following error:
> error C2057: expected constant expression

This is because VC runtime does not support VLAs

The fix is to use a C constant.