Fix Clang builds
While cross-compiling strace against libunwind for ARM, the configure
script of strace failed with:

libunwind-ptrace.h:40:27: error: a parameter list without types is only
allowed in a function definition

it turns out that we do not have a definition for what pid_t should be,
so include sys/types.h to remedy that.